language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-4.9
    - build-essential
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-ttf2.0-dev
    - libenet-dev
    - libphysfs-dev
    - libboost1.55-dev
    - scons
    - libutfcpp-dev

cache:
  apt: true


install:
  - export CXX="g++-4.9"

script: ./travis_build.script

notifications:
  email: false
