sudo: required

language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - g++-4.9
    - build-essential
    - libenet-dev
    - libphysfs-dev
    - libboost1.55-dev
    - libjsoncpp-dev
    - cmake

cache:
  apt: true

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libboost-program-options-dev 

install:
  - export CXX="g++-4.9"

script: ./travis_build.script

notifications:
  email: false
